name = "poke-ical"
main = "src/worker.ts"
compatibility_date = "2026-02-24"
compatibility_flags = ["global_fetch_strictly_public"]

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true
